### ISSUE TITLE
Info: HTML body

### ISSUE THREAD

**Issue by Schaussi** [PandaWood/Simple-MAPI.NET#1]
Nice project!
For anyone like me who needed to send HTML body content to the email client, there is a quite simple way.

Example:
```
mapi.Attach(filepath: "c:\mymail.html");
mapi.Send(subject: "a subject", noteText: null);
```

This seems to be a "hack" from older Outlook Express times.
Put your HTML content into an HTML file and attach it; set noteText to NULL; done.
Have not tested with Outlook, but it works with eM Client.

**Comment by PandaWood** [comment]
Thanks @Schaussi - yes there's some gems in amongst the old MAPI libraries
