### ISSUE TITLE
update NuGet release

### ISSUE THREAD

**Issue by schtritoff** [PandaWood/Simple-MAPI.NET#12]
Current nuget release 1.2.0 does not contain targets for .net standard and .net 6 (only net framework). Since it is Windows only lib it not a show stopper but gives compiler warnings in new projects targeting .net 5+. Please update nuget version

**Comment by PandaWood** [comment]
Thanks, yes, the nuget library is behind an update, I'll do this ASAP, in the next few days I hop

**Comment by PandaWood** [comment]
I must have forgot about this issue, looking at the latest nuget release 1.2.1, this has been done in #11
