### ISSUE TITLE
HTML content with attachments

### ISSUE THREAD

**Issue by Schaussi** [PandaWood/Simple-MAPI.NET#5]
Hi,

is there maybe a way to send HTML content (via .html file as the first attachment) **AND** additional attachments?

Attaching only a single .html file works, it will be displayed as mail content. But when I attach e.g. a PDF file in addition, both files are seen as attachment, and not only the PDF file...

Would be great if you had an approach for a way to solve this.
Thank you

**Comment by PandaWood** [comment]
Hey,

Looks like HTML content is not supported by (Simple) MAPI at all and I don't know of any hacks to do the kind of thing you're after

https://support.microsoft.com/en-us/help/268440/info-mapi-is-not-suitable-for-html-messages
